# Generated by Django 4.2.7 on 2023-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('shortContent', models.CharField(max_length=100, verbose_name='Короткий опис')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('icon', models.ImageField(upload_to='main/static/main/ArticleImgs/', verbose_name='Картинка')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публікації')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
            },
        ),
    ]
