# Generated by Django 4.2.7 on 2023-11-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_article_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='shortContent',
        ),
    ]
