# Generated by Django 4.2.7 on 2023-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_articles_shortcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Перегляди'),
        ),
    ]
