# Generated by Django 4.2.7 on 2023-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_articles_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='views',
            field=models.IntegerField(auto_created=True, default=0, verbose_name='Перегляди'),
        ),
    ]
