# Generated by Django 4.2.7 on 2023-11-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_articles_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Перегляди'),
        ),
    ]
