# Generated by Django 4.2.7 on 2023-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_articles_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('icon', models.ImageField(upload_to='main/static/main/ArticleImgs/', verbose_name='Картинка')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публікації')),
                ('views', models.IntegerField(default=0, verbose_name='Перегляди')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.RemoveField(
            model_name='articles',
            name='views',
        ),
    ]
