# Generated by Django 4.2.7 on 2023-12-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_articles_author_news_author_alter_articles_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
