# Generated by Django 4.2.7 on 2025-01-20 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_news_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='GNewsAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('requests_count', models.IntegerField(default=0, verbose_name='Requests Count')),
            ],
            options={
                'verbose_name': 'GNews API Log',
                'verbose_name_plural': 'GNews API Logs',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='is_from_gnews',
            field=models.BooleanField(default=False, verbose_name='From GNews'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Source Name'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/main/ArticleImgs/', verbose_name='Картинка'),
        ),
    ]
