# Generated by Django 4.2.7 on 2025-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_gnewsapilog_news_is_from_gnews_news_source_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL картинки'),
        ),
    ]
