# Generated by Django 4.2.7 on 2025-01-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_news_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnewsapilog',
            name='last_fetch_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Fetch Time'),
        ),
    ]
